spring.application.name=parkinglot

# ==========================
# PostgreSQL
# ==========================
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword

# ==========================
# Redis
# ==========================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ==========================
# Kafka
# ==========================
spring.kafka.bootstrap-servers=localhost:9092
# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# Consumer
spring.kafka.consumer.group-id=parking-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# ==========================
# JPA / Hibernate
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Expose Actuator endpoints
management.endpoints.web.exposure.include=health,info,metrics,prometheus

# Health endpoint details
management.endpoint.health.show-details=always

# Enable Prometheus metrics export
management.prometheus.metrics.export.enabled=true

# Common metric tags
management.metrics.tags.application=parkinglot
management.endpoints.web.base-path=/actuator
management.endpoint.prometheus.access=unrestricted
management.health.defaults.enabled=true


# logging.level.root=DEBUG


# Parking lot configuration
parking.floors=3
parking.spots.car=100
parking.spots.bike=200
parking.spots.truck=50